glasses next [display]: key(ctrl-alt-cmd-right)
glasses last [display]: key(ctrl-alt-cmd-left)
glasses right [half]: key(alt-cmd-right)
glasses left [half]: key(alt-cmd-left)
glasses (full | fullscreen): key(alt-cmd-f)