glasses next display: key(ctrl-alt-cmd-right)
glasses previous display: key(ctrl-alt-cmd-left)
glasses right half: key(alt-cmd-right)
glasses left half: key(alt-cmd-left)
glasses fullscreen: key(alt-cmd-f)