email personal : insert("adamgcog@gmail.com")
email work : insert("adamg@airkit.com")
email university : insert("aggiacca@umich.com")
dev password: insert("A1rk!t123")
dev id: insert("692f9bbd-105f-494d-86e3-62e7fe53cf31")
company name: insert("Airkit")